---
- include_vars: vars.yml
- name: Create repo folder
  become: yes
  file:
    path: /projects
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"
- name: Install base pacman packages
  become: yes
  pacman:
    state: latest
    update_cache: true
    name: "{{ pacman.base }}"