---
- include_vars: vars.yml
- name: Install pacman packages
  become: yes
  pacman:
    state: latest
    update_cache: true
    name: "{{ pacman.software-install }}"
- name: Remove packages
  pacman:
    name: "{{ pacman.software-remove }}"
    state: absent